### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by asbjornu** [PayEx/PayEx.Ecommerce.Php#2]
We should have some automatic tests that can be executed to verify that the code is in working order. [Travis](https://travis-ci.org/) can execute [PHPUnit](https://phpunit.de/) tests, so we should look into adding some of those.

**Comment by aait** [comment]
https://github.com/PayEx/PayEx.Ecommerce.Php/commit/92ea8064f4df68ad3d0872d723f4667c95d524ec
